###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: unsecure-mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=unsecure
        - MYSQL_USER=unsecure_user
        - MYSQL_PASSWORD=password
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: unsecure-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: unsecure-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini

